### ISSUE TITLE
About the Features

### ISSUE THREAD

**Issue by AshleyD707** [xuangch/CVPR22_GDLT#3]
Hi, Thank you for your great work on AQA!
I wanna to test other dataset in your model, So could you provide some code or details for the Feature extraction？

Thank you！

**Comment by xuangch** [comment]
Hi! Thank you for your attention. The code rg_swintx.py has been uploaded, and you are required to install the repo of Video Swin Transformer. Also you can refer to the supplementary material for the details of feature extraction : )

**Comment by AshleyD707** [comment]
> Hi! Thank you for your attention. The code rg_swintx.py has been uploaded, and you are required to install the repo of Video Swin Transformer. Also you can refer to the supplementary material for the details of feature extraction : )

I see.Thank you sooooo much!!
