### ISSUE TITLE
Error in train and test result

### ISSUE THREAD

**Issue by aoxipo** [xuangch/CVPR22_GDLT#4]
hi, think you for your great work!

i try to run your code to test coef but i only got 0.198.
here is my test result:
![image](https://github.com/xuangch/CVPR22_GDLT/assets/32930325/fe26aced-9aed-4152-aa4c-5e148ff53fc9)
The test results are strange. Am I not using your code correctly?
here is my test shell:
```shell
python main.py --video-path /T2004100/project/GDLK/data/GDLT_data/swintx_avg_fps25_clip32 \
    --train-label-path /T2004100/project/GDLK/data/GDLT_data/train.txt \
    --test-label-path /T2004100/project/GDLK/data/GDLT_data/test.txt  \
    --model-name mytest \
    --action-type Ball\
    --lr 1e-4 --epoch 1000 \
    --n_decoder 2 --n_query 4 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3
```

**Comment by xuangch** [comment]
Hi,
You use different hyper-parameters than us such as lr and epoch. Please refer to the README.

**Comment by aoxipo** [comment]
Sorry to bother you again, On the Fis-V dataset, Did you use the same hyper-parameters as on the RG dataset? i just train model on Fis-V dataset feature which your provide, but only got 0.3 and 0.6 ceof on TES and PCS.

**Comment by xuangch** [comment]
The hyper-parameters used for Fis-V is different from RG. All the hyper-parameters are provided in the paper (Sec. 4.2)
